### ISSUE TITLE
remember token is null

### ISSUE THREAD

**Issue by napestershine** [jayminpanchal13/laravel-multiauth-demo#2]
Hi

When I register a new admin it doesn't store remember token in in admins  table.

Can you see it please?

TIA

**Comment by prashantidealittechno** [comment]
Hello I am too not able to get the remember token in the database tables ?

**Comment by napestershine** [comment]
Well, I think that won't be a problem.

**Comment by grendeld** [comment]
@napestershine  did you resolve the problem???

**Comment by napestershine** [comment]
@grendeld Sorry We are still working on other part of project, Once we are done with that we will handle this issue too.

I will post here

**Comment by jayminpanchal** [comment]
just put `nullable()` for `remeberToken` field in migration. 

It will solve your problem. I will push my latest code with laravel 5.4
