### ISSUE TITLE
Not working with 5.4.

### ISSUE THREAD

**Issue by prashantidealittechno** [jayminpanchal13/laravel-multiauth-demo#3]
Can you please create a new repo or update the current setup to Laravel 5.4.

**Comment by napestershine** [comment]
@prashantidealittechno it's working with 5.4, I am using in my project itself. Can you share what issue are you facing ?

**Comment by keystroke99** [comment]
bro, i've installed the app in laravel 5.4. both the user and admin are working fine. the issue is form submissions is not working for admins. can you help me with that>

**Comment by napestershine** [comment]
what is the error that you are getting ?

**Comment by jayminpanchal** [comment]
@prashantidealittechno I have updated the repo to 5.4. You can check it and still has issues then let me know.
