### ISSUE TITLE
Class 'App\Http\Controllers\Admin\Auth\Auth' not found

### ISSUE THREAD

**Issue by leochung1203** [jayminpanchal13/laravel-multiauth-demo#4]
FatalErrorException in LoginController.php line 52:
Class 'App\Http\Controllers\Admin\Auth\Auth' not found
in LoginController.php line 52

Please help for the above issue

**Comment by aliwesome** [comment]
you must use _Auth Facade_  in _ Admin\Auth\LoginController_
add this line : 
`use Illuminate\Support\Facades\Auth;`
it will work 💯.

**Comment by aliwesome** [comment]
you must use Auth Facade in _Admin\Auth\LoginController_
add this line :
use Illuminate\Support\Facades\Auth;
it will work 💯.

**Comment by aliwesome** [comment]
@leochung1203 you must use Auth Facade in Admin\Auth\LoginController
add this line :
use Illuminate\Support\Facades\Auth;
it will work 💯.

**Comment by aliwesome** [comment]
@leochung1203 you must use _Auth_ Facade in _Admin\Auth\LoginController_
add this line :
`use Illuminate\Support\Facades\Auth;`
it will work. 💯

**Comment by keystroke99** [comment]
bros.. u r the life savers.. thank u very very much

**Comment by Rimon-Mahamud-Rony** [comment]
Thanks brother
