### ISSUE TITLE
There is missing something in code

### ISSUE THREAD

**Issue by allaghi** [jayminpanchal13/laravel-multiauth-demo#5]
In kernel.php file the section of : 

protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'admin.auth' => AdminRedirectIfNotAuthenticated::class,
        'admin.guest' => AdminRedirectIfAuthenticated::class,
    ];

should be :-  
protected $routeMiddleware = [
        'auth' => \Illuminate\Auth\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'bindings' => \Illuminate\Routing\Middleware\SubstituteBindings::class,
        'can' => \Illuminate\Auth\Middleware\Authorize::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'admin.auth' => \App\Http\Middleware\AdminRedirectIfNotAuthenticated::class,
        'admin.guest' =>\App\Http\Middleware\ AdminRedirectIfAuthenticated::class,
    ];

Thanks

**Comment by Versoo** [comment]
@allaghi on top of file you have:

```
use App\Http\Middleware\AdminRedirectIfAuthenticated;
use App\Http\Middleware\AdminRedirectIfNotAuthenticated;
```
And that why you don't need use path to this two Middlewares.

**Comment by allaghi** [comment]
Be honest  I didnt notice the code on top of file 😆☺
